// qa/demo-workspace/react/Home.tsx
// @ts-nocheck — declarative snippets sandbox; framework refs are intentionally uninstalled (see qa/CLAUDE.md).
// NativeScript-React (language id: typescriptreact).
// Try snippets in context: inside the returned JSX, type ns-button (→ <button>),
// ns-list-view-comp, ns-grid-layout-snippet-1, ns-tap … (React has NO ns-icon-* and
// lowercases the first letter of every tag). RootLayout / SplitView / Repeater are absent in React.
import * as React from 'react';

export function Home() {
  const onTap = () => console.log('tapped');

  return (
    <gridLayout rows="auto, *" columns="*">
      <button row={0} text="Refresh" onTap={onTap} />

      <stackLayout row={1} padding={12}>

        {/* Default */}        

        {/* Prop */}

        {/* Comp */}

      </stackLayout>
    </gridLayout>
  );
}

// qa/demo-workspace/svelte/Home.svelte
<!-- Svelte Native (language id: svelte).
     Try snippets in context: type ns-button (→ <button>), ns-slider-prop
     (→ bind:value), ns-segmented-bar-prop (→ bind:selectedIndex), ns-long-press …
     Svelte lowercases the first letter of every tag and has NO ns-icon-* snippets. -->
<page>
  <actionBar title="NativeScript Snippets — Svelte demo" />
  <gridLayout rows="auto, *" columns="*">
    <button row={0} text="Refresh" on:tap={onTap} />

    <stackLayout row={1} padding="12">

      <!-- Default -->

      <!-- Prop -->

      <!-- Comp -->

    </stackLayout>
  </gridLayout>
</page>

<script>
  function onTap() {
    console.log('tapped');
  }
</script>
