// qa/demo-workspace/vue/Home.vue
<!-- NativeScript-Vue SFC (language id: vue).
     Try snippets in context: inside <template>, type ns-button, ns-list-view-comp,
     ns-grid-layout-snippet-1, ns-swipe … (Vue has NO ns-icon-* snippets). -->
<template>
  <Page>
    <ActionBar title="NativeScript Snippets — Vue demo" />
    <GridLayout rows="auto, *" columns="*">
      <Button row="0" text="Refresh" @tap="onTap" />

      <ListView row="1" for="item in items">
        <v-template>
          <StackLayout orientation="horizontal" padding="12">
            <Label :text="item.name" />

            <!-- Default -->

            <!-- Prop -->

            <!-- Comp -->
             
          </StackLayout>
        </v-template>
      </ListView>
    </GridLayout>
  </Page>
</template>

<script>
export default {
  data() {
    return { items: [{ name: 'Alpha' }, { name: 'Beta' }, { name: 'Gamma' }] };
  },
  methods: {
    onTap() {
      console.log('tapped');
    },
  },
};
</script>

// qa/demo-workspace/svelte/Home.svelte
<!-- Svelte Native (language id: svelte).
     Try snippets in context: type ns-button (→ <button>), ns-slider-prop
     (→ bind:value), ns-segmented-bar-prop (→ bind:selectedIndex), ns-long-press …
     Svelte lowercases the first letter of every tag and has NO ns-icon-* snippets. -->
<page>
  <actionBar title="NativeScript Snippets — Svelte demo" />
  <gridLayout rows="auto, *" columns="*">
    <button row={0} text="Refresh" on:tap={onTap} />

    <stackLayout row={1} padding="12">

      <!-- Default -->

      <!-- Prop -->

      <!-- Comp -->

    </stackLayout>
  </gridLayout>
</page>

<script>
  function onTap() {
    console.log('tapped');
  }
</script>
