// qa/workspace/svelte/Bindings.svelte
<!-- Svelte flavor (language id: svelte) — two-way / event-naming delta scratch.
     Use this file for the section that contrasts -prop two-way bindings
     (bind:value, bind:selectedIndex) against the -comp event attributes
     (on:valueChange, on:selectedIndexChanged). Put the cursor on a blank
     line below and type the -prop / -comp prefix under test. -->
<page>
  <stackLayout>

    <!-- type here -->

  </stackLayout>
</page>

<script>
  // component logic
</script>

// qa/workspace/vue/Bindings.vue
<!-- Vue flavor — scratch for the flavor-delta section (one-way attributes only).
     Use this file to confirm Vue has NO two-way binding shape:
       - ns-slider-prop  -> value="${3:number}"  (plain attribute, never bind:/[(x)])
       - ns-text-field-prop -> text="${27:string}"
     and to confirm event attrs use @name="${n}" (ns-button-comp -> @tap="${24}").

     Put the cursor on the blank "type here" line inside <template>. Cmd+Z after each. -->
<template>
  <Page>
    <StackLayout>

      <!-- type here -->

    </StackLayout>
  </Page>
</template>

<script>
export default {};
</script>
