// qa/workspace/react/Home.tsx
// React flavor (language id: typescriptreact) — NativeScript-React (JSX).
// Put the cursor on a blank "type here" line inside the returned JSX and type
// an ns-* prefix, then accept the completion.
//
// Tag case is LOWERCASE-FIRST: ns-button -> <button>, ns-stack-layout -> <stackLayout>.
// Events are onTap={...} / onCheckedChange={...}. There is NO two-way binding.
// React has NO icon snippets (ns-icon-* must NOT appear).
export function Home() {
  return (
    <stackLayout>

      {/* type here */}

    </stackLayout>
  );
}

// qa/workspace/vue/Home.vue
<!-- Vue flavor (language id: vue) — NativeScript-Vue SFC.
     Put the cursor on a blank "type here" line inside <template> and type an
     ns-* prefix (e.g. ns-button, ns-button-prop, ns-button-comp, ns-swipe).
     Accept with Tab/Enter, then Cmd+Z before the next case.

     Vue facts this fixture proves:
       - PascalCase tags (ns-button -> <Button>)
       - property attrs  name="${n:hint}"
       - event attrs     @name="${n}"   (NO two-way binding)
       - NO icon snippets (ns-icon-* must NOT appear here). -->
<template>
  <Page>
    <ActionBar title="QA" />
    <StackLayout>

      <!-- type here -->

    </StackLayout>
  </Page>
</template>

<script>
export default {};
</script>
