// qa/workspace/general/scratch.tsx
// React flavor (language id: typescriptreact) — NativeScript-React (JSX).
// Put the cursor inside the returned JSX and type an ns-* prefix
// (e.g. ns-button → <button></button> — note the LOWERCASE tag).
// React has NO icon snippets (ns-icon-* must not appear).
export function Scratch() {
  return (
    <stackLayout>

      {/* type here */}

    </stackLayout>
  );
}

// qa/workspace/general/scratch.vue
<!-- Vue flavor (language id: vue) — NativeScript-Vue SFC.
     Put the cursor on a blank line inside <template> and type an ns-* prefix
     (e.g. ns-button, ns-swipe). Vue has NO icon snippets (ns-icon-* must not appear). -->
<template>
  <Page>
    <StackLayout>

      <!-- type here -->

    </StackLayout>
  </Page>
</template>

<script>
export default {};
</script>
