// qa/workspace/general/scratch.svelte
<!-- Svelte flavor (language id: svelte) — Svelte Native component.
     Put the cursor on a blank line inside the markup and type an ns-* prefix
     (e.g. ns-button → <button> — note the LOWERCASE tag; ns-slider-prop → bind:value).
     Svelte has NO icon snippets (ns-icon-* must not appear). -->
<page>
  <stackLayout>

    <!-- type here -->

  </stackLayout>
</page>

<script>
</script>

// qa/workspace/general/scratch.vue
<!-- Vue flavor (language id: vue) — NativeScript-Vue SFC.
     Put the cursor on a blank line inside <template> and type an ns-* prefix
     (e.g. ns-button, ns-swipe). Vue has NO icon snippets (ns-icon-* must not appear). -->
<template>
  <Page>
    <StackLayout>

      <!-- type here -->

    </StackLayout>
  </Page>
</template>

<script>
export default {};
</script>
