// qa/workspace/general/scratch.svelte
<!-- Svelte flavor (language id: svelte) — Svelte Native component.
     Put the cursor on a blank line inside the markup and type an ns-* prefix
     (e.g. ns-button → <button> — note the LOWERCASE tag; ns-slider-prop → bind:value).
     Svelte has NO icon snippets (ns-icon-* must not appear). -->
<page>
  <stackLayout>

    <!-- type here -->

  </stackLayout>
</page>

<script>
</script>

// qa/workspace/general/scratch.jsx
// React flavor (language id: javascriptreact) — same snippets as .tsx.
// Put the cursor inside the returned JSX and type an ns-* prefix
// (e.g. ns-button → <button></button> — LOWERCASE tag).
export function Scratch() {
  return (
    <stackLayout>

      {/* type here */}

    </stackLayout>
  );
}
