// qa/workspace/svelte/Home.svelte
<!-- Svelte flavor (language id: svelte) — NativeScript-Svelte component.
     Put the cursor on a blank line below and type an ns-* prefix
     (e.g. ns-button -> <button>, ns-stack-layout-snippet-1, ns-longPress),
     then accept the completion and verify the expansion + tab stops.
     Svelte has NO icon snippets (ns-icon-* must not appear). -->
<page>
  <stackLayout>

    <!-- type here -->

  </stackLayout>
</page>

<script>
  // component logic
</script>

// qa/workspace/react/Home.tsx
// React flavor (language id: typescriptreact) — NativeScript-React (JSX).
// Put the cursor on a blank "type here" line inside the returned JSX and type
// an ns-* prefix, then accept the completion.
//
// Tag case is LOWERCASE-FIRST: ns-button -> <button>, ns-stack-layout -> <stackLayout>.
// Events are onTap={...} / onCheckedChange={...}. There is NO two-way binding.
// React has NO icon snippets (ns-icon-* must NOT appear).
export function Home() {
  return (
    <stackLayout>

      {/* type here */}

    </stackLayout>
  );
}
