// qa/workspace/vue/Home.vue
<!-- Vue flavor (language id: vue) — NativeScript-Vue SFC.
     Put the cursor on a blank "type here" line inside <template> and type an
     ns-* prefix (e.g. ns-button, ns-button-prop, ns-button-comp, ns-swipe).
     Accept with Tab/Enter, then Cmd+Z before the next case.

     Vue facts this fixture proves:
       - PascalCase tags (ns-button -> <Button>)
       - property attrs  name="${n:hint}"
       - event attrs     @name="${n}"   (NO two-way binding)
       - NO icon snippets (ns-icon-* must NOT appear here). -->
<template>
  <Page>
    <ActionBar title="QA" />
    <StackLayout>

      <!-- type here -->

    </StackLayout>
  </Page>
</template>

<script>
export default {};
</script>

// qa/workspace/react/Home.jsx
// React flavor (language id: javascriptreact) — same snippets as Home.tsx.
// Both .tsx and .jsx map to the SAME react snippet files in package.json,
// so every case in react.md should behave identically here.
//
// Put the cursor on a blank "type here" line inside the returned JSX, type an
// ns-* prefix, accept. Tag case is LOWERCASE-FIRST (<button>, <stackLayout>);
// events are onTap={...}; NO two-way binding; NO icon snippets (ns-icon-*).
export function Home() {
  return (
    <stackLayout>

      {/* type here */}

    </stackLayout>
  );
}
